collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#261D20'
    - '#8A8985'
    - '#902431'
    - '#EFC2A2'
  rhythmicContrast: 1
typography_spectrum: 0.3853047
layout_spectrum: 1
name: Westernsydneywanderers
